package courseregistrationsystem.entity;
// Generated May 18, 2021 7:59:37 PM by Hibernate Tools 4.3.1



/**
 * Account generated by hbm2java
 */
public class Account  implements java.io.Serializable {

     private String hoten;
     private String username;
     private String password;

    public Account() {
    }

    public Account(String username, String password) {
       this.username = username;
       this.password = password;
    }
   
    public String getHoten() {
        return hoten;
    }

    public void setHoten(String hoten) {
        this.hoten = hoten;
    }

    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }




}