package courseregistrationsystem.entity;
// Generated May 18, 2021 7:59:37 PM by Hibernate Tools 4.3.1



/**
 * Course generated by hbm2java
 */
public class Course  implements java.io.Serializable {


     private Integer courseId;
     private String subjectId;
     private String subjectName;
     private int credits;
     private String gvlt;
     private String room;
     private String thu;
     private String ca;
     private int slots;
     private String semName;
     private int year;

    public Course() {
    }

    public Course(String subjectId, String subjectName, int credits, String gvlt, String room, String thu, String ca, int slots, String semName, int year) {
       this.subjectId = subjectId;
       this.subjectName = subjectName;
       this.credits = credits;
       this.gvlt = gvlt;
       this.room = room;
       this.thu = thu;
       this.ca = ca;
       this.slots = slots;
       this.semName = semName;
       this.year = year;
    }
   
    public Integer getCourseId() {
        return this.courseId;
    }
    
    public void setCourseId(Integer courseId) {
        this.courseId = courseId;
    }
    public String getSubjectId() {
        return this.subjectId;
    }
    
    public void setSubjectId(String subjectId) {
        this.subjectId = subjectId;
    }
    public String getSubjectName() {
        return this.subjectName;
    }
    
    public void setSubjectName(String subjectName) {
        this.subjectName = subjectName;
    }
    public int getCredits() {
        return this.credits;
    }
    
    public void setCredits(int credits) {
        this.credits = credits;
    }
    public String getGvlt() {
        return this.gvlt;
    }
    
    public void setGvlt(String gvlt) {
        this.gvlt = gvlt;
    }
    public String getRoom() {
        return this.room;
    }
    
    public void setRoom(String room) {
        this.room = room;
    }
    public String getThu() {
        return this.thu;
    }
    
    public void setThu(String thu) {
        this.thu = thu;
    }
    public String getCa() {
        return this.ca;
    }
    
    public void setCa(String ca) {
        this.ca = ca;
    }
    public int getSlots() {
        return this.slots;
    }
    
    public void setSlots(int slots) {
        this.slots = slots;
    }
    public String getSemName() {
        return this.semName;
    }
    
    public void setSemName(String semName) {
        this.semName = semName;
    }
    public int getYear() {
        return this.year;
    }
    
    public void setYear(int year) {
        this.year = year;
    }




}


