package courseregistrationsystem.entity;
// Generated May 18, 2021 7:59:37 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * RegisterSession generated by hbm2java
 */
public class RegisterSession  implements java.io.Serializable {


     private Integer sessionId;
     private Date startDay;
     private Date endDay;
     private String semNameFk;
     private int yearFk;

    public RegisterSession() {
    }

    public RegisterSession(Date startDay, Date endDay, String semNameFk, int yearFk) {
       this.startDay = startDay;
       this.endDay = endDay;
       this.semNameFk = semNameFk;
       this.yearFk = yearFk;
    }
   
    public Integer getSessionId() {
        return this.sessionId;
    }
    
    public void setSessionId(Integer sessionId) {
        this.sessionId = sessionId;
    }
    public Date getStartDay() {
        return this.startDay;
    }
    
    public void setStartDay(Date startDay) {
        this.startDay = startDay;
    }
    public Date getEndDay() {
        return this.endDay;
    }
    
    public void setEndDay(Date endDay) {
        this.endDay = endDay;
    }
    public String getSemNameFk() {
        return this.semNameFk;
    }
    
    public void setSemNameFk(String semNameFk) {
        this.semNameFk = semNameFk;
    }
    public int getYearFk() {
        return this.yearFk;
    }
    
    public void setYearFk(int yearFk) {
        this.yearFk = yearFk;
    }




}


