package courseregistrationsystem.entity;
// Generated May 18, 2021 7:59:37 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Semester generated by hbm2java
 */
public class Semester  implements java.io.Serializable {


     private SemesterId id;
     private Date startDay;
     private Date endDay;
     private boolean currentSem;

    public Semester() {
    }

    public Semester(SemesterId id, Date startDay, Date endDay, boolean currentSem) {
       this.id = id;
       this.startDay = startDay;
       this.endDay = endDay;
       this.currentSem = currentSem;
    }
   
    public SemesterId getId() {
        return this.id;
    }
    
    public void setId(SemesterId id) {
        this.id = id;
    }
    public Date getStartDay() {
        return this.startDay;
    }
    
    public void setStartDay(Date startDay) {
        this.startDay = startDay;
    }
    public Date getEndDay() {
        return this.endDay;
    }
    
    public void setEndDay(Date endDay) {
        this.endDay = endDay;
    }
    public boolean isCurrentSem() {
        return this.currentSem;
    }
    
    public void setCurrentSem(boolean currentSem) {
        this.currentSem = currentSem;
    }




}


