package courseregistrationsystem.entity;
// Generated May 18, 2021 7:59:37 PM by Hibernate Tools 4.3.1



/**
 * SemesterId generated by hbm2java
 */
public class SemesterId  implements java.io.Serializable {


     private String semName;
     private int year;

    public SemesterId() {
    }

    public SemesterId(String semName, int year) {
       this.semName = semName;
       this.year = year;
    }
   
    public String getSemName() {
        return this.semName;
    }
    
    public void setSemName(String semName) {
        this.semName = semName;
    }
    public int getYear() {
        return this.year;
    }
    
    public void setYear(int year) {
        this.year = year;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof SemesterId) ) return false;
		 SemesterId castOther = ( SemesterId ) other; 
         
		 return ( (this.getSemName()==castOther.getSemName()) || ( this.getSemName()!=null && castOther.getSemName()!=null && this.getSemName().equals(castOther.getSemName()) ) )
 && (this.getYear()==castOther.getYear());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getSemName() == null ? 0 : this.getSemName().hashCode() );
         result = 37 * result + this.getYear();
         return result;
   }   


}


