package courseregistrationsystem.entity;
// Generated May 18, 2021 7:59:37 PM by Hibernate Tools 4.3.1



/**
 * StudentCourseId generated by hbm2java
 */
public class StudentCourseId  implements java.io.Serializable {


     private String studentId;
     private int courseId;

    public StudentCourseId() {
    }

    public StudentCourseId(String studentId, int courseId) {
       this.studentId = studentId;
       this.courseId = courseId;
    }
   
    public String getStudentId() {
        return this.studentId;
    }
    
    public void setStudentId(String studentId) {
        this.studentId = studentId;
    }
    public int getCourseId() {
        return this.courseId;
    }
    
    public void setCourseId(int courseId) {
        this.courseId = courseId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof StudentCourseId) ) return false;
		 StudentCourseId castOther = ( StudentCourseId ) other; 
         
		 return ( (this.getStudentId()==castOther.getStudentId()) || ( this.getStudentId()!=null && castOther.getStudentId()!=null && this.getStudentId().equals(castOther.getStudentId()) ) )
 && (this.getCourseId()==castOther.getCourseId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getStudentId() == null ? 0 : this.getStudentId().hashCode() );
         result = 37 * result + this.getCourseId();
         return result;
   }   


}


