package courseregistrationsystem.entity;
// Generated May 18, 2021 7:59:37 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * StudentCourse generated by hbm2java
 */
public class StudentCourse  implements java.io.Serializable {


     private StudentCourseId id;
     private Date regisTime;

    public StudentCourse() {
    }

    public StudentCourse(StudentCourseId id, Date regisTime) {
       this.id = id;
       this.regisTime = regisTime;
    }
   
    public StudentCourseId getId() {
        return this.id;
    }
    
    public void setId(StudentCourseId id) {
        this.id = id;
    }
    public Date getRegisTime() {
        return this.regisTime;
    }
    
    public void setRegisTime(Date regisTime) {
        this.regisTime = regisTime;
    }




}


