package courseregistrationsystem.entity;
// Generated May 18, 2021 7:59:37 PM by Hibernate Tools 4.3.1



/**
 * Student generated by hbm2java
 */
public class Student  implements java.io.Serializable {


     private String studentId;
     private String name;
     private String sex;
     private String telephone;
     private String classId;
     private String password;

    public Student() {
    }

	
    public Student(String studentId, String name, String sex, String password) {
        this.studentId = studentId;
        this.name = name;
        this.sex = sex;
        this.password = password;
    }
    public Student(String studentId, String name, String sex, String telephone, String classId, String password) {
       this.studentId = studentId;
       this.name = name;
       this.sex = sex;
       this.telephone = telephone;
       this.classId = classId;
       this.password = password;
    }
   
    public String getStudentId() {
        return this.studentId;
    }
    
    public void setStudentId(String studentId) {
        this.studentId = studentId;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getSex() {
        return this.sex;
    }
    
    public void setSex(String sex) {
        this.sex = sex;
    }
    public String getTelephone() {
        return this.telephone;
    }
    
    public void setTelephone(String telephone) {
        this.telephone = telephone;
    }
    public String getClassId() {
        return this.classId;
    }
    
    public void setClassId(String classId) {
        this.classId = classId;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }




}


