/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package courseregistrationsystem.ui;

import courseregistrationsystem.dao.CourseDAO;
import courseregistrationsystem.dao.SemesterDAO;
import courseregistrationsystem.dao.StudentCourseDAO;
import courseregistrationsystem.dao.SharedData;
import courseregistrationsystem.entity.Course;
import courseregistrationsystem.entity.Semester;
import courseregistrationsystem.entity.StudentCourse;
import courseregistrationsystem.entity.StudentCourseId;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author dinhp
 */
public class CourseRegistrationJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CourseRegistrationJPanel
     */
    public CourseRegistrationJPanel() {
        initComponents();
        LoadData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblCourses = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        btnRegistrateCourse = new javax.swing.JButton();
        btnDeleteCourse = new javax.swing.JButton();

        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        tblCourses.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã môn", "Tên môn", "Số tín chỉ", "GVLT", "Phòng", "Thứ", "Ca", "Sỉ số tối đa", "Đăng kí"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblCourses.setColumnSelectionAllowed(true);
        jScrollPane3.setViewportView(tblCourses);
        tblCourses.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        if (tblCourses.getColumnModel().getColumnCount() > 0) {
            tblCourses.getColumnModel().getColumn(0).setPreferredWidth(25);
            tblCourses.getColumnModel().getColumn(2).setPreferredWidth(150);
            tblCourses.getColumnModel().getColumn(3).setPreferredWidth(50);
            tblCourses.getColumnModel().getColumn(5).setPreferredWidth(35);
            tblCourses.getColumnModel().getColumn(6).setPreferredWidth(30);
            tblCourses.getColumnModel().getColumn(7).setPreferredWidth(25);
            tblCourses.getColumnModel().getColumn(8).setPreferredWidth(70);
            tblCourses.getColumnModel().getColumn(9).setPreferredWidth(50);
        }

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Đăng Kí Học Phần");

        btnRegistrateCourse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/courseregistrationsystem/icon/icon-48-dkhp.png"))); // NOI18N
        btnRegistrateCourse.setText("Đăng kí");
        btnRegistrateCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrateCourseActionPerformed(evt);
            }
        });

        btnDeleteCourse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/courseregistrationsystem/icon/Actions-edit-delete-icon-16.png"))); // NOI18N
        btnDeleteCourse.setText("Xóa");
        btnDeleteCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteCourseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 615, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(btnRegistrateCourse)
                        .addGap(14, 14, 14)
                        .addComponent(btnDeleteCourse)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jSeparator1))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(255, 255, 255)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegistrateCourse)
                    .addComponent(btnDeleteCourse))
                .addGap(53, 53, 53))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    private boolean checkNumberRegisteredCourse(){
        int count = 0;
        for(int i = 0; i < tblCourses.getRowCount(); i++){
            Boolean regis;
            regis = tblCourses.getValueAt(i, 9) != null ? (Boolean) tblCourses.getValueAt(i, 9) : false ;
            
            if(regis){
                count++;
            }
        }
        if (count <= 8)
            return true;
        else
            return false;
    }
    
    private boolean checkTime(){
        CourseDAO dao = new CourseDAO();
        List<Course> courseList = new ArrayList();
        for(int i = 0; i < tblCourses.getRowCount(); i++){
            Boolean regis;
            regis = tblCourses.getValueAt(i, 9) != null ? (Boolean) tblCourses.getValueAt(i, 9) : false ;
        
            if(regis){
                Course course = dao.findCourse(Integer.parseInt( tblCourses.getValueAt(i, 0).toString()));
                courseList.add(course);
            }
        }
        
        for(int i = 0; i < courseList.size() - 1; i++){
            for(int j = i + 1; j < courseList.size(); j++){
                if(courseList.get(i).getThu().equals(courseList.get(j).getThu()) && 
                        (courseList.get(i).getCa().equals(courseList.get(j).getCa())))
                        return false;
                    
            }
        }
        return true;
    }
    
    private void btnRegistrateCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrateCourseActionPerformed
        SimpleDateFormat fm = new SimpleDateFormat("MM/dd/yyyy hh:mm:ss");
        CourseDAO dao = new CourseDAO();
        StudentCourseDAO sdao = new StudentCourseDAO();
        LocalDateTime current = LocalDateTime.now();
        
        if(checkNumberRegisteredCourse()){
            if (checkTime()){
                for(int i = 0; i < tblCourses.getRowCount(); i++){
                    Boolean regis = tblCourses.getValueAt(i, 9) != null ? (Boolean) tblCourses.getValueAt(i, 9) : false ;

                    if (regis){
                        Course course = dao.findCourse(Integer.parseInt( tblCourses.getValueAt(i, 0).toString()));
                        StudentCourse sc = new StudentCourse();
                        StudentCourseId id = new StudentCourseId();

                        id.setStudentId(SharedData.student.getStudentId());
                        id.setCourseId(course.getCourseId());
                        sc.setId(id);
                        try {
                            Date regisTime = fm.parse(fm.format(java.sql.Timestamp.valueOf(current)));
                            sc.setRegisTime(regisTime);
                        } catch (ParseException ex) {
                            Logger.getLogger(CourseRegistrationJPanel.class.getName()).log(Level.SEVERE, null, ex);
                        }
                        if(sdao.saveStudentCourse(sc)){
                            //JOptionPane.showMessageDialog(null, "Đăng kí thành công");
                        }
                    }
                }
                JOptionPane.showMessageDialog(null, "Đăng kí thành công");
            }else{
                  JOptionPane.showMessageDialog(null, "Tồn tại 2 môn trùng giờ học");
                  LoadData();
                    }
        }else{
            JOptionPane.showMessageDialog(null, "Đăng kí tối đa 8 môn");
            LoadData();
        }
    }//GEN-LAST:event_btnRegistrateCourseActionPerformed

    private void btnDeleteCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteCourseActionPerformed
        StudentCourseDAO dao = new StudentCourseDAO();
        int id = tblCourses.getSelectedRow();
        StudentCourseId studentCourseId = new StudentCourseId(SharedData.student.getStudentId(), Integer.parseInt(tblCourses.getValueAt(id, 0).toString()));
        
        if(dao.deleteStudentCourse(dao.findStudentCourse(studentCourseId))){
            JOptionPane.showMessageDialog(null, "Xóa thành công");
            LoadData();
        }
    }//GEN-LAST:event_btnDeleteCourseActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        LoadData();
    }//GEN-LAST:event_formComponentShown
    
    private boolean checkRegistered(int courseId){
        StudentCourseDAO dao = new StudentCourseDAO();
        StudentCourseId studentCourseId = new StudentCourseId(SharedData.student.getStudentId(), courseId);
        
        if(dao.findStudentCourse(studentCourseId) != null){
            return true;
        }
        
        return false;
    }
    public void LoadData(){
        CourseDAO std = new CourseDAO();
        SemesterDAO sdao = new SemesterDAO();
        Semester semesterCurrent = null;
        DefaultTableModel dtm = (DefaultTableModel) tblCourses.getModel();
        dtm.setNumRows(0);
        
        for(Semester t : sdao.findAll()){
            if (t.isCurrentSem()) {
                semesterCurrent = t;
            }
        }
        
        for(Course st : std.findAll()){
            if(st.getSemName().toString().equals(semesterCurrent.getId().getSemName()) && 
                    (st.getYear() == semesterCurrent.getId().getYear())){
                dtm.addRow(new Object[]{st.getCourseId(), st.getSubjectId(), st.getSubjectName(), st.getCredits(), st.getGvlt(),
                        st.getRoom(), st.getThu(), st.getCa(), st.getSlots(),checkRegistered(st.getCourseId()) ? true:false});
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDeleteCourse;
    private javax.swing.JButton btnRegistrateCourse;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable tblCourses;
    // End of variables declaration//GEN-END:variables
}
