/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package courseregistrationsystem.ui;

import courseregistrationsystem.dao.SharedData;


/**
 *
 * @author dinhp
 */
public class ManagerForm extends javax.swing.JFrame {
    private StudentManagementPanel mStudentPanel = null;
    private AccountManagementPanel mAccountPanel = null;
    private SubjectManagementPanel mSubjectPanel = null;
    private SemesterManagementPanel mSemesterPanel = null;
    private ClassManagementPanel mClassPanel = null;
    private SessionManagementPanel mSessionPanel = null;
    private CourseManagementPanel mCoursePanel = null;
    private OverviewPanel overViewPanel = null;
    public ManagerForm() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        lbUsername = new javax.swing.JLabel();
        btnLogout = new javax.swing.JButton();
        btnChangePassword = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        btnManementAccount = new javax.swing.JButton();
        btnManementStudent = new javax.swing.JButton();
        btnManementSubject = new javax.swing.JButton();
        btnManementSemester = new javax.swing.JButton();
        btnManementClass = new javax.swing.JButton();
        btnManementRegister = new javax.swing.JButton();
        btnManementCourse = new javax.swing.JButton();
        btnOverview = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Hệ thống đăng kí học phần");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jToolBar1.setRollover(true);

        lbUsername.setForeground(new java.awt.Color(255, 0, 0));
        lbUsername.setText("giaovu");
        lbUsername.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                lbUsernamePropertyChange(evt);
            }
        });
        jToolBar1.add(lbUsername);

        btnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/courseregistrationsystem/icon/Login-icon-32.png"))); // NOI18N
        btnLogout.setText("Đăng xuất");
        btnLogout.setFocusable(false);
        btnLogout.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnLogout.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        jToolBar1.add(btnLogout);

        btnChangePassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/courseregistrationsystem/icon/gpa-icon-32.png"))); // NOI18N
        btnChangePassword.setText("Đổi mật khẩu");
        btnChangePassword.setFocusable(false);
        btnChangePassword.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnChangePassword.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnChangePassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangePasswordActionPerformed(evt);
            }
        });
        jToolBar1.add(btnChangePassword);
        jToolBar1.add(jSeparator1);

        btnManementAccount.setIcon(new javax.swing.ImageIcon(getClass().getResource("/courseregistrationsystem/icon/Person-Male-Light-icon-24.png"))); // NOI18N
        btnManementAccount.setText("Quản lý tài khoản");
        btnManementAccount.setFocusable(false);
        btnManementAccount.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnManementAccount.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnManementAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManementAccountActionPerformed(evt);
            }
        });
        jToolBar1.add(btnManementAccount);

        btnManementStudent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/courseregistrationsystem/icon/10207-man-student-light-skin-tone-icon-24.png"))); // NOI18N
        btnManementStudent.setText("Quản lý sinh viên");
        btnManementStudent.setFocusable(false);
        btnManementStudent.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnManementStudent.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnManementStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManementStudentActionPerformed(evt);
            }
        });
        jToolBar1.add(btnManementStudent);

        btnManementSubject.setIcon(new javax.swing.ImageIcon(getClass().getResource("/courseregistrationsystem/icon/Actions-document-edit-icon-24.png"))); // NOI18N
        btnManementSubject.setText("Quản lý môn học");
        btnManementSubject.setFocusable(false);
        btnManementSubject.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnManementSubject.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnManementSubject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManementSubjectActionPerformed(evt);
            }
        });
        jToolBar1.add(btnManementSubject);

        btnManementSemester.setIcon(new javax.swing.ImageIcon(getClass().getResource("/courseregistrationsystem/icon/Manage_semester.png"))); // NOI18N
        btnManementSemester.setText("Quản lý học kì");
        btnManementSemester.setFocusable(false);
        btnManementSemester.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnManementSemester.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnManementSemester.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManementSemesterActionPerformed(evt);
            }
        });
        jToolBar1.add(btnManementSemester);

        btnManementClass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/courseregistrationsystem/icon/kisspng-school-pictograms-icon-teacher-icon-classroom-icon-5d40763ee263d5.5330674915645056629273.png"))); // NOI18N
        btnManementClass.setText("Quản lý lớp");
        btnManementClass.setFocusable(false);
        btnManementClass.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnManementClass.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnManementClass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManementClassActionPerformed(evt);
            }
        });
        jToolBar1.add(btnManementClass);

        btnManementRegister.setIcon(new javax.swing.ImageIcon(getClass().getResource("/courseregistrationsystem/icon/icon-48-dkhp.png"))); // NOI18N
        btnManementRegister.setText("Quản lý kì ĐKHP");
        btnManementRegister.setFocusable(false);
        btnManementRegister.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnManementRegister.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnManementRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManementRegisterActionPerformed(evt);
            }
        });
        jToolBar1.add(btnManementRegister);

        btnManementCourse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/courseregistrationsystem/icon/icon-48-study.png"))); // NOI18N
        btnManementCourse.setText("Quản lý học phần");
        btnManementCourse.setFocusable(false);
        btnManementCourse.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnManementCourse.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnManementCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManementCourseActionPerformed(evt);
            }
        });
        jToolBar1.add(btnManementCourse);

        btnOverview.setIcon(new javax.swing.ImageIcon(getClass().getResource("/courseregistrationsystem/icon/Actions-view-choose-icon-24.png"))); // NOI18N
        btnOverview.setText("Tổng quan ");
        btnOverview.setFocusable(false);
        btnOverview.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnOverview.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnOverview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOverviewActionPerformed(evt);
            }
        });
        jToolBar1.add(btnOverview);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 823, Short.MAX_VALUE)
                    .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 458, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        this.setVisible(false);
        LoginDialog loginDialog = new LoginDialog(this, rootPaneCheckingEnabled);
        loginDialog.setVisible(true);
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnManementAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManementAccountActionPerformed
        if(mAccountPanel == null){
            mAccountPanel = new AccountManagementPanel();
            jTabbedPane1.add("Quản lý tài khoản",mAccountPanel);
        }
        jTabbedPane1.setSelectedComponent(mAccountPanel);
        mAccountPanel.LoadData();
    }//GEN-LAST:event_btnManementAccountActionPerformed

    private void btnManementStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManementStudentActionPerformed
        if(mStudentPanel == null){
            mStudentPanel = new StudentManagementPanel();
            jTabbedPane1.add("Quản lý sinh viên",mStudentPanel);
        }
        jTabbedPane1.setSelectedComponent(mStudentPanel);
        mStudentPanel.LoadData("Tất cả");
    }//GEN-LAST:event_btnManementStudentActionPerformed

    private void btnManementSemesterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManementSemesterActionPerformed
        if(mSemesterPanel == null){
            mSemesterPanel = new SemesterManagementPanel();
            jTabbedPane1.add("Quản lý học kì",mSemesterPanel);
        }
        jTabbedPane1.setSelectedComponent(mSemesterPanel);     
        mSemesterPanel.LoadData();
    }//GEN-LAST:event_btnManementSemesterActionPerformed

    private void btnManementRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManementRegisterActionPerformed
        if(mSessionPanel == null){
            mSessionPanel = new SessionManagementPanel();
            jTabbedPane1.add("Quản lý kì đăng kí",mSessionPanel);
        }
        jTabbedPane1.setSelectedComponent(mSessionPanel);
        mSessionPanel.LoadData();
    }//GEN-LAST:event_btnManementRegisterActionPerformed

    private void btnOverviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOverviewActionPerformed
        // overViewPanel
        if(overViewPanel == null){
            overViewPanel = new OverviewPanel();
            jTabbedPane1.add("Tổng quan",overViewPanel);
        }
        jTabbedPane1.setSelectedComponent(overViewPanel);
        //mSessionPanel.LoadData();
    }//GEN-LAST:event_btnOverviewActionPerformed

    private void btnChangePasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangePasswordActionPerformed
        ChangePasswordForm changePasswordForm = new ChangePasswordForm();
        changePasswordForm.setVisible(true);
        
    }//GEN-LAST:event_btnChangePasswordActionPerformed

    private void btnManementClassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManementClassActionPerformed
        if (mClassPanel == null) {
            mClassPanel = new ClassManagementPanel();
            jTabbedPane1.add("Quản lý lớp học", mClassPanel);
        }
        jTabbedPane1.setSelectedComponent(mClassPanel);
        mClassPanel.LoadData();
    }//GEN-LAST:event_btnManementClassActionPerformed

    private void lbUsernamePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_lbUsernamePropertyChange
        // TODO add your handling code here:    
    }//GEN-LAST:event_lbUsernamePropertyChange

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        lbUsername.setText(SharedData.manager.getUsername());
    }//GEN-LAST:event_formWindowOpened

    private void btnManementSubjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManementSubjectActionPerformed
        if(mSubjectPanel == null){
            mSubjectPanel = new SubjectManagementPanel();
            jTabbedPane1.add("Quản lý môn học",mSubjectPanel);
        }
        jTabbedPane1.setSelectedComponent(mSubjectPanel);
        mSubjectPanel.LoadData();
    }//GEN-LAST:event_btnManementSubjectActionPerformed

    private void btnManementCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManementCourseActionPerformed
        if(mCoursePanel == null){
            mCoursePanel = new CourseManagementPanel();
            jTabbedPane1.add("Quản lý học phần",mCoursePanel);
        }
        jTabbedPane1.setSelectedComponent(mCoursePanel);
        mCoursePanel.LoadData();
    }//GEN-LAST:event_btnManementCourseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManagerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManagerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManagerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManagerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManagerForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChangePassword;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnManementAccount;
    private javax.swing.JButton btnManementClass;
    private javax.swing.JButton btnManementCourse;
    private javax.swing.JButton btnManementRegister;
    private javax.swing.JButton btnManementSemester;
    private javax.swing.JButton btnManementStudent;
    private javax.swing.JButton btnManementSubject;
    private javax.swing.JButton btnOverview;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel lbUsername;
    // End of variables declaration//GEN-END:variables
}
